### ISSUE TITLE
ReadMe.md motion detector link is broken

### ISSUE THREAD

**Issue by mdw7326** [Philipps-Organization/securityCam#124]
The link that was pointing to the motion detector on amazon.com is broken

**Comment by philippschulte** [comment]
You just have to search in amazon for arduino motion sensor. Actually you can connect any motion sensor with an arduino controller. 

That's the motion sensor I've used for my project:
http://www.amazon.com/gp/product/B00FDPO9B8?keywords=arduino%20motion%20sensor&qid=1445863874&ref_=sr_1_1&sr=8-1

Cheers,
Philipp

**Comment by mdw7326** [comment]
Thanks! Just wanted to point out the link. Great project!
